бардак развёл
dl-academy-edu/sp-korneenko-dmitry pull request #5
Opened 2020-01-21 13:20 UTC by PhillipJeffries

помоги прибраться, пожалуйста)

2020-01-21 16:43 UTC, SergeyPechinov requested changes

2020-01-21 16:43 UTC, SergeyPechinov commented on Personal-project/index.html
> +            <button>join</button>
Стоит обернуть в форму и кнопку сделать submit'ом

2020-01-21 16:43 UTC, SergeyPechinov commented on Personal-project/index.html
> +    ,300i,400,400i,600,600i,700,700i,800&display=swap" rel="stylesheet">
не стоит грузить полностью шрифты, можно выбирать жирность шрифта и начертание (если в проекте используется только 700 жирность, не стоит грузить 400, 500 и т.д.).
Пример:
![image](https://user-images.githubusercontent.com/47389103/72823618-6de4fc00-3c8d-11ea-927b-1225d08b6bc2.png)

2020-01-21 16:43 UTC, SergeyPechinov commented on Personal-project/index.html
>      </section>
Постер не может быть секцией т.к. это слайдер (section должен содержать в себе заголовок h2-h6), либо делать каждый слайд в отдельную секцию, но я бы сделал просто дивами. Из за того, что это слайдер, в нем не может быть h1 (h1 должен быть 1 на странице, не больше, но желательно, что бы он был).

2020-01-21 16:43 UTC, SergeyPechinov commented on Personal-project/index.html
> +            <a href="#" class="italic">Credit</a>
Это переключатели, нужно делать кнопкой

2020-01-22 13:42 UTC, PhillipJeffries commented on Personal-project/index.html
> +    ,300i,400,400i,600,600i,700,700i,800&display=swap" rel="stylesheet">
я на всякий случай загрузил)

2020-01-22 13:46 UTC, PhillipJeffries commented on Personal-project/index.html
>      </section>
не знаю пока про слайдеры ничего. Я тут не нашёл ярко-выраженного заголовка, почему-то

2020-01-22 13:46 UTC, PhillipJeffries commented on Personal-project/index.html
> +            <a href="#" class="italic">Credit</a>
ок

2020-01-25 08:04 UTC, merged